AWSTemplateFormatVersion: 2010-09-09
Description: Creates a VPC with public and private subnets
Parameters:
  AvailabilityZone1:
    Type: String
    Default: us-east-1a  
  AvailabilityZone2:
    Type: String
    Default: us-east-1b
  AvailabilityZone3:
    Type: String
    Default: us-east-1c
  AvailabilityZone4:
    Type: String
    Default: us-east-1d
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: Dev   
    AllowedValues:
    - Prod
    - Dev
    - QA 
  EmployeeID:
    Description: EmployeeID
    Type: String
    Default: Dev     
  EmployeeContact:
    Description: Contact of the Employee 
    Type: String
    Default: Dev     
  LOB:
    Description: Line of business
    Type: String
    Default: DEVOPS     
    AllowedValues:
    - DBA
    - DEVOPS
    - SYSADMIN
    - CLOUD     
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.34.0.0/16
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZone1
      CidrBlock: 172.34.1.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-VPCA'
        - Key: EmployeeID
          Value: !Sub '${EmployeeID}'  
        - Key: EmployeeContact
          Value: !Sub '${EmployeeContact}' 
        - Key: LOB
          Value: !Sub '${LOB}'       
  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZone2
      CidrBlock: 172.34.3.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC      
  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZone3
      CidrBlock: 172.34.2.0/24
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZone4
      CidrBlock: 172.34.4.0/24
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC     
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
  PublicRouteTable:
    DependsOn: AttachGateway
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  PublicDefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable
  PublicRouteAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnetA
  PublicRouteAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnetB
#ASG
  WebServerSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Allows inbound http traffic
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
      Tags:
        - Key: Name
          Value: http
  LoadBalancer:
    Type: 'AWS::ElasticLoadBalancing::LoadBalancer'
    Properties:
      LoadBalancerName: LoadBalancer
      Listeners:
        - InstancePort: 80
          InstanceProtocol: HTTP
          LoadBalancerPort: 80
          Protocol: HTTP
      Scheme: internet-facing
      SecurityGroups:
        - !Ref WebServerSG
      Subnets:
        - !Ref PublicSubnetA
        - !Ref PublicSubnetB
  AppLaunchConfiguration:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      AssociatePublicIpAddress: true
      ImageId: 'ami-0dd387866de2504e4' 
      InstanceType: t2.micro
      SecurityGroups: []
    DependsOn: AttachGateway
  AppASG:  
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      Cooldown: '2400'    
      AvailabilityZones:
        - !Ref AvailabilityZone1
        - !Ref AvailabilityZone2
      DesiredCapacity: 2
      HealthCheckGracePeriod: '2400'
      HealthCheckType: ELB
      LaunchConfigurationName: !Ref AppLaunchConfiguration
      LoadBalancerNames: !Ref LoadBalancer
      MaxSize: 4
      MinSize: 2  
      VPCZoneIdentifier:
        - !Ref PublicSubnetA
        - !Ref PublicSubnetB          
      
        